version: '3'
services:
  postgres:
    container_name: 'ddemo_postgres'
    restart: 'always'
    image: 'postgres:12.1'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ddemo-datavolume:/var/lib/postgresql/data
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./src/DDemo.Api
    depends_on: 
      - postgres
    ports:
      - '8888:80'

volumes:
  ddemo-datavolume: